services:
  mcp-context7:
    build:
      context: ./mcp-context7
      args:
        USER_UID: "${DEV_UID}"
        USER_GID: "${DEV_GID}"
    restart: unless-stopped
    volumes:
      - mcp-context7-sock:/run/mcp-context7
    env_file:
      - ${CONTEXT7_ENV_FILE} # Credentials - see scripts/lib/env.sh)
    # UIDs mapping - Rootless Podman remaps container UIDs through /etc/subuid/subgid
    # Use keep-id for a 1:1 mapping to have host's values when running useradd in Dockerfile
    userns_mode: keep-id

  mcp-thiri:
    build:
      context: ./mcp-thiri
      args:
        USER_UID: "${DEV_UID}"
        USER_GID: "${DEV_GID}"
    restart: unless-stopped
    volumes:
      - mcp-thiri-sock:/run/mcp-thiri
    env_file:
      - ${THIRI_ENV_FILE} # Credentials - see scripts/lib/env.sh)
    userns_mode: keep-id

volumes:
  mcp-context7-sock:
    name: mcp-context7-sock
  mcp-thiri-sock:
    name: mcp-thiri-sock
